[project]
name = "engram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bunker D", email = "contact@bunkerd.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.2",
]

[project.optional-dependencies]
gui = [
    "pyside6>=6.8.2",
]

[tool.ruff.lint]
select = ["E", "F", "ANN"]
ignore = ["E731"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-dparam>=1.0.0",
    "ruff>=0.9.4",
    "engram[gui]",
]
